name: Quality Gate
on:
  push:
    branches:
      - master
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
jobs:
  build:
    name: SonarQube Scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Scanning
        run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectBaseDir=${{ env.GITHUB_WORKSPACE }} -Dsonar.qualitygate.wait=true
